#!/bin/bash

###
### Builds an entire stage
###
####
#### Usage: build-stage {stage#}
####
#### stage# is the stage number (1, 2 or 3)
####

STAGE="$1"

source $(dirname "$0")/private/dirs.inc.sh

echo "Building stage ${STAGE}..."

for build in $(find "${BUILDS_DIR}" -name "${STAGE}.*.build" -exec basename {} \; | cut -d . -f 1 --complement | sort -g | awk '{ sub("([0-9]+[.])?", ""); sub("[.]build$", ""); print }'); do
  if ! $SCRIPTS_DIR/build $build all; then
    echo "Error building $build" >&2
    exit 1
  fi
done
