#!/bin/bash

###
### CPIO index generator
###
####
#### Usage: gen-cpio-index
####

source $(dirname "$0")/dirs.inc.sh

exec 3>$(dirname "$0")/../linux-*/cpio-mayal.txt

ldconfig -n -r "$INITRAMFS_DIR" /lib /lib64 /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64

for f in $(find "$INITRAMFS_DIR" -type d | tail -n +2); do
  dirpath=$(echo "$f" | awk "{ sub(\"$INITRAMFS_DIR\", \"\"); print }")

  echo "dir $dirpath 755 0 0" >&3
done

other_dirs=(/dev /newroot /sys /proc /run)

for d in ${other_dirs[*]}; do
  echo "dir $d 755 0 0" >&3
done

for f in $(find "$INITRAMFS_DIR" -type f); do
  fpath=$(echo "$f" | awk "{ sub(\"$INITRAMFS_DIR\", \"\"); print }")

  echo "file $fpath $(realpath "$f") $(stat --printf="%a" "$f") 0 0" >&3
done

for f in $(find "$INITRAMFS_DIR" -type l); do
  lpath=$(echo "$f" | awk "{ sub(\"$INITRAMFS_DIR\", \"\"); print }")
  
  echo "slink $lpath $(readlink $f) $(stat --printf="%a" "$f") 0 0" >&3
done

echo "file /init $OTHER_DIR/init-script.sh 744 0 0"
echo >&3

# Console
echo "nod /dev/console 600 0 0 c 5 1" >&3

exec 3>&-
