#!/bin/bash

###
### Initramfs generator
###
####
#### Usage: gen-initramfs
####

# Source files are hard-linked, not copied, thus MUST NOT be modified in initramfs directory
sources=(bin/mv bin/cp bin/umount bin/mount bin/mkdir bin/chroot bin/ls bin/rmdir bin/rm bin/mknod bin/bash bin/mkfifo sbin/switch_root sbin/pivot_root) 
shared_libraries=(libc libuuid libmount libattr libncursesw libblkid ld libdl)

source $(dirname "$0")/dirs.inc.sh

$(dirname "$0")/build-stage 1

[[ ! -d "$INITRAMFS_DIR" ]] && echo "ERROR: initramfs directory not found." >&2 && exit 1

pushd "$INITRAMFS_DIR" >/dev/null
rm -rf *

mkdir -p etc bin sbin lib usr/lib usr/local/lib

ln -s lib lib64
ln -s ../lib usr/lib
ln -s ../lib usr/lib64
ln -s ../../lib usr/local/lib
ln -s ../../lib usr/local/lib64

for f in ${sources[*]}; do
  cp -l "$ENV_DIR/$f" "$INITRAMFS_DIR/$f"
done

for slib in ${shared_libraries[*]}; do
  if ! cp -l $(find $ENV_DIR/{lib,lib64,/usr/lib,/usr/lib64} -name "$slib*.so*" -type f -perm /700 -printf "%p " 2>/dev/null) "$INITRAMFS_DIR/lib/" 2>/dev/null; then
    echo "Error while copying library $slib" >&2
    exit 1
  fi
done

popd >/dev/null

if ! $(dirname "$0")/gen-cpio-index; then
  echo "Unable to generate cpio index" >&2
  exit 1
fi

make -C $(find $(dirname "$0")/../ -maxdepth 1 -name 'linux-*' -type d)
