#!/bin/bash

###
### This script clears the build environment
###
#### Author: Alfredo Mungo <chimeranet89@gmail.com>
####
#### Usage: groundup y
####
#### y must be used to ensure this is not an accidental command issue
####

source $(dirname "$0")/dirs.inc.sh

[[ "$1" != y ]] && echo "SECURE LOCK: aborting..." && exit 1

# Wait 5 seconds before starting
echo "5 seconds to cleanup. Hit ^C to abort..."
echo -n ">>>"

for i in 5 4 3 2 1; do
	echo -n " $i"
	sleep 1
done

echo
echo

# Clean old files
echo "Removing old directories..."
rm -rf ${ENV_DIR} ${PKG_DIR} ${STG_DIR} ${BLD_DIR} ${BUILD_DIR} ${CACHE_DIR}
