#!/bin/bash

###
### This script clears the build environment
###
#### Author: Alfredo Mungo <chimeranet89@gmail.com>
####
#### Usage: groundup y
####
#### y must be used to ensure this is not an accidental command issue
####

source $(dirname "$0")/dirs.inc.sh

[[ "$1" != y ]] && echo "SECURE LOCK: aborting..." && exit 1

# Wait 5 seconds before starting
echo "5 seconds to cleanup. Hit ^C to abort..."
echo -n ">>>"

for i in 5 4 3 2 1; do
	echo -n " $i"
	sleep 1
done

echo
echo

# Clean old files
echo "Removing old directories..."
rm -rf ${ENV_DIR} ${STAGES_DIR} ${STG_DIR} ${INSTALL_DIR} ${BUILD_DIR} ${CACHE_DIR}

# Remove kernel
find $BASE_DIR/ -name 'linux-*' -max-depth 1 -type d -exec rm -rf {} +

# Setup configuration files
mkdir -p "${ENV_DIR}" >/dev/null
pushd ${ENV_DIR}
tar -xvf "${OTHER_DIR}/misc-config.tar.xz"
popd >/dev/null

# Setup package database
echo Creating new package database structure...
sqlite3 $DB_PACKAGES <<EOF
.bail on
DROP TABLE IF EXISTS packages;
DROP TABLE IF EXISTS shared_objects;

CREATE TABLE packages(name VARCHAR(256) NOT NULL, version VARCHAR(32) NOT NULL, file VARCHAR(1024), build_date INTEGER DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(name, version)) WITHOUT ROWID;
CREATE TABLE shared_objects(package_name VARCHAR(256) NOT NULL, package_version VARCHAR(32) NOT NULL, libfile VARCHAR(1024) NOT NULL, PRIMARY KEY(package_name, package_version, libfile), FOREIGN KEY(package_name, package_version) REFERENCES packages(name, version)) WITHOUT ROWID;
EOF

# Delete shared obejcts database
rm -f $DB_SHARED
