#!/bin/bash

###
### This script installs kernel and modules in the package directory
###
####
#### Author: Alfredo Mungo <chimeranet89@gmail.com>
####
#### Usage: kernel-install kernel-version
####
#### kernel-version is the complete kernel version, i.e.: 3.13.3
####

exec 3>/dev/null

# Constants
PKG_DIR=/tmp/pkg

# Arguments
KNL_VER="$1"

# Check arguments
[[ -z "$KNL_VER" ]] && echo "ERROR: kernel version not provided" >&2 && exit 1

# Set data
KNL_DIR=$(realpath $(dirname $0)/linux-${KNL_VER})
KNL_OUT_FILE="vmlinuz-${KNL_VER}-wise"

# Check directories
[[ ! -d "$KNL_DIR" ]] && echo "ERROR: kernel directory <${KNL_DIR}> does not exist" >&2 && exit 1

# Create directories
echo "Populating directory hierarchy..."

mkdir -p ${PKG_DIR}/{boot,lib} || (echo "ERROR: unable to create directory structure" && exit 2)

# Install files
echo "Installing kernel files..."
cp "${KNL_DIR}/arch/x86/boot/bzImage" "${PKG_DIR}/boot/${KNL_OUT_FILE}"
cp "${KNL_DIR}/System.map" "${PKG_DIR}/boot/"
make -C "${KNL_DIR}" INSTALL_MOD_PATH=${PKG_DIR} modules_install >&3

# Create links
pushd "${PKG_DIR}/boot" >&3
ln -s ${KNL_OUT_FILE} vmlinuz >&3
popd >&3

# Install headers
echo "Installing headers..."
make -C "${KNL_DIR}" headers_install >&3

