#!/bin/bash

###
### Configuration files maker
###
####
#### Author: Alfredo Mungo <chimeranet89@gmail.com>
####
#### Usage: mkconf
####

source $(dirname "$0")/dirs.inc.sh
exec 3>/dev/null

# Check environment
[[ ! -d "$INSTALL_DIR" ]] && echo "ERROR: Packaging directory <${INSTALL_DIR}> does not exist" >&2 && exit 1

pushd $INSTALL_DIR >&3
tar xvf $STAGES_DIR/stageP/misc-config.tar.xz
popd >&3
