#!/bin/bash

###
### Configuration files maker
###
####
#### Author: Alfredo Mungo <chimeranet89@gmail.com>
####
#### Usage: mkconf
####

source $(dirname "$0")/dirs.inc.sh
exec 3>/dev/null

# Check environment
[[ ! -d "$BLD_DIR" ]] && echo "ERROR: Packaging directory <${BLD_DIR}> does not exist" >&2 && exit 1

pushd $BLD_DIR >&3
tar xvf $PKG_DIR/stageP/misc-config.tar.xz
popd >&3
