#!/bin/bash

###
### Package creator
###
### Creates a .tar.xz package from directory and copies it into stage directory
###
#### Author: Alfredo Mungo <chimeranet89@gmail.com>
####
#### Usage: pack {stage#} {pack-name}
####
#### stage# is the stage number (1, 2 or 3)
#### pack-name is the package name (e.g.: linux-3.13.3)

source $(dirname "$0")/dirs.inc.sh
exec 3>/dev/null

# Set args
STAGE=$1
PKG_NAME=$2
STAGE_DIR="${STAGES_DIR}/stage${STAGE}"

# Check environment
[[ ! -d "$INSTALL_DIR" ]] && echo "ERROR: Packaging directory <${INSTALL_DIR}> does not exist" >&2 && exit 1
[[ ! -d "$STAGE_DIR" ]] && echo "ERROR: Stage directory <${STAGE_DIR}> does not exist" >&2 && exit 1

# Check args
[[ -z "$STAGE" ]] && echo "ERROR: Missing stage number" >&2 && exit 1
[[ -z "$PKG_NAME" ]] && echo "ERROR: Missing package name" >&2 && exit 1

case "$STAGE" in
1 | 2 | 3 | P ) ;;
* )
	echo "ERROR: Stage must be 1, 2, 3 or P" >&2
	exit 1
	;;
esac

# Generate dependencies
$(realpath -L -P $(dirname "$0"))/showdepends

# Create output filename
PKG_FILE="${PKG_NAME}.tar.xz"
PKG_PATH="${STAGE_DIR}/${PKG_FILE}"

echo "Creating package ${PKG_FILE}:"

# Compress package
echo "- Compressing..."

pushd "${INSTALL_DIR}" >&3
(tar --recursion -cJvf "$PKG_PATH" * | awk '{ print ">> " $0; }') || (echo "ERROR: Unable to create compressed tarball" >&2 && exit 2)
popd >&3

echo
# Display size stats
echo -n "- * Original size: "
du -h "$INSTALL_DIR" | tail -n 1 | awk '{ print $1; }'
echo -n "- * Packed size: "
du -h "$PKG_PATH" | awk '{ print $1; }'

# Display shared dependencies
if [[ -f "$DEP_LOGFILE" ]]; then
  echo
  echo "- Shared object dependencies"
  awk '{ print ">> " $0; }' <<EOF
$(for f in $(cat $DEP_LOGFILE); do echo "$f -> $(sqlite3 $BASE_DIR/shared-objects.sqlite "select * from so where library like '$(echo $f | cut -d . -f 1,2)%'")"; done)
EOF
fi

echo
# Clean-up
echo "- Cleaning up..."
rm -rf ${INSTALL_DIR}/*
