#!/bin/bash

###
### This scripts sets the stage links to the selected stage
###
#### Author: Alfredo Mungo <chimeranet89@gmail.com>
####
#### Usage: setstage {stage#}
####
#### stage# is the stage number. Must be 1, 2 or 3
####

source $(dirname "$0")/dirs.inc.sh
exec 3>/dev/null

# Arguments
STAGE=$1

# Check arguments
[[ -z "$STAGE" ]] && echo "ERROR: No stage specified" >&2 && exit 1

# Set stage
echo "Setting stage ${STAGE}..."
rm -f ${STG_DIR}/*

for pkgf in $BUILDS_DIR/${STAGE}.*; do
	ln -s "$(realpath $pkgf)" "${STG_DIR}/"
done
