#!/bin/bash

###
### This scripts sets the stage links to the selected stage
###
#### Author: Alfredo Mungo <chimeranet89@gmail.com>
####
#### Usage: setstage {stage#}
####
#### stage# is the stage number. Must be 1, 2 or 3
####

exec 3>/dev/null

# Constants
STG_DIR=./stage
DEV_DIR=./devel

# Arguments
STAGE=$1

# Check arguments
[[ -z "$STAGE" ]] && echo "ERROR: No stage specified" >&2 && exit 1

# Set data
STAGE_DIR="${DEV_DIR}/stage${STAGE}"

# Check devel directory
[[ ! -d "$STAGE_DIR" ]] && echo "ERROR: Unknown stage directory <${STAGE_DIR}>" >&2 && exit 1

# Set stage
echo "Setting stage ${STAGE}..."
rm -f ${STG_DIR}/*

for pkgf in $STAGE_DIR/*; do
	ln -s "$(realpath $pkgf)" "${STG_DIR}/"
done

