#!/bin/bash

###
### Show dynamic library dependencies of a ready to be packed package
###
####
#### Usage: showdepends
####

source $(dirname "$0")/dirs.inc.sh
cd $BASE_DIR

exec 4>"$DEP_LOGFILE"

function needed() {
  for f in $(find $INSTALL_DIR/{bin,sbin,lib,lib64,usr/bin,usr/sbin,usr/lib,usr/lib64,usr/local/bin,usr/local/sbin,usr/local/lib,usr/local/lib64} -type f -executable 2>/dev/null); do
    objdump -w -p "$f" 2>/dev/null | grep NEEDED | sed -e 's/[ \t]*//g' -e 's/NEEDED//'
  done
}

needed | sort -u >&4

exec 4>&-
